version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=db
    volumes:
      - pgdata:/data/postgres
    networks:
      - nesjs-network
    
  api:
    build: .
    container_name: api
    ports: 
      - 3000:3000
    networks:
      - nesjs-network
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    depends_on:
      - database

networks:
  nesjs-network:
  
volumes:
  pgdata:
    driver: local